from fpdf import FPDF
from datetime import datetime
from .. import models

class VulnoraReport(FPDF):
    def header(self):
        self.set_font("Arial", "B", 15)
        self.cell(0, 10, "Vulnora Penetration Test & Vulnerability Assessment Report", ln=1, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Generated by Vulnora • {datetime.now().strftime('%Y-%m-%d %H:%M UTC')} • Ethical Use Only", 0, 0, "C")

def generate_pdf_report(scan: models.Scan) -> bytes:
    pdf = VulnoraReport()
    pdf.add_page()
    pdf.set_font("Arial", "B", 12)

    pdf.cell(0, 10, f"Target: {scan.target}", ln=1)
    pdf.cell(0, 10, f"Scan Date: {scan.time.strftime('%Y-%m-%d %H:%M UTC')}", ln=1)
    pdf.cell(0, 10, f"Overall Risk Score: {scan.risk_score}/10", ln=1)
    pdf.ln(10)

    # Findings
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Discovered Vulnerabilities", ln=1)
    pdf.set_font("Arial", "", 10)

    nuclei = scan.result_data.get("nuclei", []) if isinstance(scan.result_data, dict) else []
    for finding in nuclei:
        sev = finding.get("severity", "medium").upper()
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, f"[{sev}] {finding.get('name')}", ln=1)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 6, f"ID: {finding.get('id')} | CVSS: {finding.get('cvss_score', 0)}\n")
        pdf.multi_cell(0, 6, f"Description: {finding.get('description', 'N/A')}\n")
        pdf.multi_cell(0, 6, f"Remediation: {finding.get('remediation', 'N/A')}\n")
        pdf.ln(4)

    # Global Compliance Mapping
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Global Compliance Mapping", ln=1)
    pdf.set_font("Arial", "", 10)
    for finding in nuclei:
        sev = finding.get("severity", "medium").lower()
        mapping = COMPLIANCE_MAP.get(sev, "Review recommended under ISO 27001 / NIST CSF")
        pdf.multi_cell(0, 6, f"• {finding.get('name')} ({sev.upper()}) → {mapping}")
        pdf.ln(3)

    pdf.ln(10)
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, "Report generated by Vulnora – Real vulnerability scanning platform for ethical penetration testing and GRC.", 0, 1, "C")

    return pdf.output(dest="S").encode("latin-1")
