# backend/app/report.py
from fpdf import FPDF
from datetime import datetime
from .. import models
from ..constants import COMPLIANCE_MAP

class VulnoraReport(FPDF):
    def header(self):
        self.set_font("Arial", "B", 15)
        self.cell(0, 10, "Vulnora Penetration Test & Vulnerability Assessment Report", ln=1, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Generated by Vulnora • {datetime.now().strftime('%Y-%m-%d %H:%M UTC')} • Ethical Use Only", 0, 0, "C")

    def add_logic_finding(self, finding: dict):
        """Helper to nicely format logic flaw findings"""
        sev = finding.get("severity", "medium").upper()
        self.set_font("Arial", "B", 11)
        self.cell(0, 8, f"[{sev}] {finding.get('name', 'Logic Flaw')}", ln=1)
        self.set_font("Arial", "", 10)
        
        desc = finding.get("description", "N/A")
        self.multi_cell(0, 6, f"Description: {desc}\n")
        
        poc = finding.get("poc", {})
        if poc:
            self.multi_cell(0, 6, f"Proof of Concept: {str(poc)[:500]}...\n")
        
        self.ln(5)

def generate_pdf_report(scan: models.Scan) -> bytes:
    pdf = VulnoraReport()
    pdf.add_page()
    pdf.set_font("Arial", "B", 12)

    # Header Information
    pdf.cell(0, 10, f"Target: {scan.target}", ln=1)
    pdf.cell(0, 10, f"Scan Date: {scan.time.strftime('%Y-%m-%d %H:%M UTC') if hasattr(scan, 'time') else 'N/A'}", ln=1)
    pdf.cell(0, 10, f"Overall Risk Score: {scan.risk_score}/10", ln=1)
    pdf.ln(15)

    # === NUCLEI FINDINGS (Original Section - Unchanged) ===
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Nuclei Template Findings", ln=1)
    pdf.set_font("Arial", "", 10)

    nuclei = []
    if isinstance(scan.result_data, dict):
        nuclei = scan.result_data.get("nuclei", []) or []

    if nuclei:
        for finding in nuclei:
            sev = finding.get("severity", "medium").upper()
            pdf.set_font("Arial", "B", 11)
            pdf.cell(0, 8, f"[{sev}] {finding.get('name', 'Unnamed')}", ln=1)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 6, f"ID: {finding.get('id')} | CVSS: {finding.get('cvss_score', 0):.1f}\n")
            pdf.multi_cell(0, 6, f"Description: {finding.get('description', 'N/A')}\n")
            pdf.multi_cell(0, 6, f"Remediation: {finding.get('remediation', 'No remediation provided')}\n")
            pdf.ln(5)
    else:
        pdf.cell(0, 10, "No Nuclei findings detected.", ln=1)
        pdf.ln(5)

    # === LOGIC FLAWS FINDINGS (NEW FULL SECTION) ===
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Logic Flaws & Business Logic Vulnerabilities", ln=1)
    pdf.ln(5)
    pdf.set_font("Arial", "", 10)

    logic_findings = []
    if isinstance(scan.result_data, dict):
        logic_findings = scan.result_data.get("logic_flaws", []) or []

    if logic_findings:
        for finding in logic_findings:
            pdf.add_logic_finding(finding)
    else:
        pdf.cell(0, 10, "No logic flaws detected in this scan.", ln=1)
        pdf.ln(5)

    # Compliance Mapping (kept for Nuclei, extended slightly for logic)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Compliance & Risk Mapping", ln=1)
    pdf.set_font("Arial", "", 10)
    pdf.ln(5)

    for finding in nuclei:
        sev = finding.get("severity", "medium").lower()
        mapping = COMPLIANCE_MAP.get(sev, "Review under relevant frameworks (OWASP, NIST, etc.)")
        pdf.multi_cell(0, 6, f"• {finding.get('name')} ({sev.upper()}) → {mapping}")
        pdf.ln(3)

    if logic_findings:
        pdf.ln(5)
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Logic Flaws Compliance Note:", ln=1)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 6, "Logic flaws often map to OWASP Top 10 (A01, A02, A05, A08) and require business logic review. "
                             "High/Critical findings should be validated manually with impact assessment.")

    pdf.ln(15)
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, "Report generated by Vulnora – Real open-source vulnerability scanning platform.", 0, 1, "C")

    return pdf.output(dest="S").encode("latin-1")
